#!/usr/bin/env bash
set -e

echo 'User data:'
gh api user --jq '.login, .name,.email'
echo -e -n '\nUser Scopes: '
gh api rate_limit --include --silent | grep 'X-Oauth-Scopes:' | sed 's/X-Oauth-Scopes: //g'

echo -e -n '\nToken Type: '
token=$(gh auth token)
if [[ $token == ghp_* ]]; then
  echo 'PAT'
elif [[ $token == github_pat_* ]]; then
  echo 'PATV2-Fine Grained Tokens'
elif [[ $token == gho_* ]]; then
  echo 'OAuth'
elif [[ $token == ghu_* ]]; then
    echo 'User to Server Token'
elif [[ $token == ghs_* ]]; then
        echo 'Server to Server Token'
elif [[ $token == ghr_* ]]; then
        echo 'Refresh Token'        
else
  echo 'Unknown'
fi

